sudo: required

services:
  - docker

before_install:
  - docker build -t digitalronin/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run digitalronin/client-test npm run test -- --coverage

after_success:
  - docker build -t digitalronin/multi-client ./client
  - docker build -t digitalronin/multi-nginx ./nginx
  - docker build -t digitalronin/multi-server ./server
  - docker build -t digitalronin/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push digitalronin/multi-client
  - docker push digitalronin/multi-nginx
  - docker push digitalronin/multi-server
  - docker push digitalronin/multi-worker

deploy:
  on:
    branch: master
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "udemy-multi"
  env: "UdemyMulti-env"
  bucket_name: "elasticbeanstalk-us-west-2-351222107032"
  bucket_path: "udemy-multi"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
